Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: wp
    SupplierDeployMetadata:
      RoleName: ${RoleName}
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: wordpress
          Url: 'ros_templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 1c1g
              Parameters:
                Vcpu: "1"
                Memory: 1Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
            - Name: 基础版
              Description: 2c2g
              Parameters:
                Vcpu: "2"
                Memory: 2Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
            - Name: 高配版
              Description: 2c4g
              Parameters:
                Vcpu: "2"
                Memory: 4Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
          HiddenParameterKeys:
            - ClusterId
            - Vcpu
            - Memory
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                ${RegionId}:
                  Parameters:
                    ClusterId: ${ClusterId}
    TemplateConfigs:
      - Name: wordpress
        AllowedRegions:
          - ${RegionId}
        ArchitectureDiagramUrl: 'docs/architecture.png'
        UpdateInfo:
          ParametersAllowedToBeModified:
            - ReplicaCount
            - Storage
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: wordpress
        Operation:
          - Name: 更改套餐
            Description: 更改套餐规格
            Type: Custom
            SupportPredefinedParameters: true
            EnableLogging: false
          - Name: 扩容磁盘
            Description: mysql磁盘扩容
            Type: Upgrade
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - Storage
          - Name: 更改副本数
            Description: 更改wordpress副本数
            Type: Custom
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - ReplicaCount
    StatusOperationConfigs:
      - TemplateName: wordpress
        DeployScene: ACK
        Parameters:
          - ReplicaCount
        SupportOperations:
          - Start
          - Stop
          - Restart
  ServiceType: managed
  IsSupportOperated: true
  PolicyNames: AliyunComputeNestPolicyForOperation
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: WordPress 容器多租户yaml部署
    Image: 'resources/icons/service_logo.png'
    Name: Wordpress 容器yaml部署
  ShareType: Public
  ApprovalType: Manual