Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: wp-
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{ computenest::helmchart::wordpress }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
      RoleName: ${RoleName}
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: wordpress
          Url: 'ros_templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 低配版
              Parameters:
                Vcpu: 300m
                Memory: 512Mi
                Storage: 20Gi
                ReplicaCount: 1
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
                - ReplicaCount
            - Name: 基础版
              Description: 基础版
              Parameters:
                Vcpu: 600m
                Memory: 1Gi
                Storage: 40Gi
                ReplicaCount: 2
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
                - ReplicaCount
            - Name: 高配版
              Description: 高配版
              Parameters:
                Vcpu: '1'
                Memory: 2Gi
                Storage: 80Gi
                ReplicaCount: 3
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
                - ReplicaCount
          HiddenParameterKeys:
            - ClusterId
            - Vcpu
            - Memory
            - Storage
            - ReplicaCount
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                ${RegionId}:
                  Parameters:
                    ClusterId: ${ClusterId}
    TemplateConfigs:
      - Name: wordpress
        AllowedRegions:
          - ${RegionId}
        ArchitectureDiagramUrl: 'docs/architecture.png'
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: WordPress 容器多租户yaml部署
    Image: 'resources/icons/service_logo.png'
    Name: Wordpress 容器yaml部署
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: HelmChart
    ArtifactName: HelmChart-Wordpress
    Description: wordpress HelmChart部署物
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.HelmChart_1.RepoName}
      Tag: ${HelmChartBuilder.HelmChart_1.Tag}
      RepoType: Public
HelmChartBuilder:
  HelmChart_1:
    HelmChartPath: 'resources/artifact_resources/helm_chart/wordpress-15.4.1.tgz'
    RepoName: wordpress
    Tag: 15.4.1